---
driver:
  name: docker
  privileged: true
  use_sudo: false

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:  
      run_command: /usr/lib/systemd/systemd

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

suites:
  - name: default
    run_list:
      - recipe[lcd_study::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
